# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-14 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=20)),
                ('penulis', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('blog', 'blog'), ('berita', 'berita'), ('jurnal', 'jurnal')], default='blog', max_length=20)),
                ('body', models.TextField()),
                ('ditulis', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
